# Generated by Django 2.0 on 2018-01-09 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auto_20180109_1832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='ename',
            new_name='name',
        ),
    ]
