# Generated by Django 2.0 on 2018-01-09 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_auto_20180109_1833'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='public_holidays',
            new_name='public_holiday',
        ),
    ]
