# Generated by Django 2.0 on 2018-01-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_auto_20180109_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='staff',
            fields=[
                ('staff_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='employee', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='staff_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_casual_leave', models.IntegerField()),
                ('max_compensation_leave', models.IntegerField()),
                ('max_earned_leave', models.IntegerField()),
                ('max_half_pay_leave', models.IntegerField()),
                ('max_leave_with_allowance', models.IntegerField()),
                ('max_duty_leave', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.DeleteModel(
            name='public_holiday',
        ),
        migrations.DeleteModel(
            name='employee',
        ),
        migrations.AddField(
            model_name='staff',
            name='category',
            field=models.ForeignKey(on_delete=None, to='attendance.staff_category'),
        ),
    ]
