# Generated by Django 2.0 on 2018-01-11 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_auto_20180111_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_category',
            name='category',
            field=models.CharField(choices=[('RA', 'Regular Academic'), ('RNA', 'Regular Non-Academic'), ('C1', 'Contract Staff (1 yr)'), ('C6', 'Contract Staff (6 month)'), ('AS', 'Ad-hoc Staff'), ('PF', 'Part time Staff'), ('OT', 'Office Trainee'), ('DT', 'Department Trainee')], default='RA', max_length=3),
        ),
    ]
