# Generated by Django 2.0 on 2018-01-11 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_auto_20180111_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present_days', models.IntegerField(default=0)),
                ('casual_leave', models.IntegerField(default=0)),
                ('compensation_leave', models.IntegerField(default=0)),
                ('earned_leave', models.IntegerField(default=0)),
                ('half_pay_leave', models.IntegerField(default=0)),
                ('leave_allowance', models.IntegerField(default=0)),
                ('duty_leave', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='staff',
            name='joining_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='staff',
            name='termination_date',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='leave',
            name='emp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.staff'),
        ),
    ]
