# Generated by Django 2.0 on 2018-01-13 06:58

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_staff_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='rec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2018, 1, 13, 6, 58, 52, 905389, tzinfo=utc))),
                ('status', models.IntegerField(choices=[(0, 'A'), (1, 'P'), (2, 'CL'), (3, 'ComL'), (4, 'EL'), (5, 'HPL'), (6, 'LA'), (7, 'DL')], default='-1')),
                ('time_in', models.DateTimeField(null=True)),
                ('time_out', models.DateTimeField(null=True)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.staff')),
            ],
        ),
    ]
