# Generated by Django 2.0 on 2018-01-29 14:43

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0014_auto_20180124_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='dept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(choices=[('H', 'HOD'), ('P', 'Principal')], max_length=5)),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.staff')),
            ],
        ),
        migrations.CreateModel(
            name='leave_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2018, 1, 29, 14, 43, 51, 577184, tzinfo=utc))),
                ('type', models.IntegerField(choices=[(0, 'A'), (1, 'P'), (2, 'CL'), (3, 'ComL'), (4, 'EL'), (5, 'HPL'), (6, 'LA'), (7, 'DL')], default=2)),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.staff')),
            ],
        ),
        migrations.AlterField(
            model_name='rec',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 1, 29, 14, 43, 51, 575266, tzinfo=utc)),
        ),
    ]
