# Generated by Django 2.0 on 2018-01-29 16:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0015_auto_20180129_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave_request',
            name='is_accepted',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='leave_request',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 1, 29, 16, 4, 2, 20568, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rec',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 1, 29, 16, 4, 2, 18928, tzinfo=utc)),
        ),
    ]
