# Generated by Django 2.0 on 2018-01-29 16:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0016_auto_20180129_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave_request',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 1, 29, 16, 58, 6, 1125, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rec',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 1, 29, 16, 58, 5, 999123, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rec',
            name='status',
            field=models.BooleanField(default=1),
        ),
    ]
