# Generated by Django 2.0 on 2018-02-24 09:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0019_auto_20180207_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='is_hod',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staff',
            name='is_principal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='leave_request',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='leave_request',
            name='type',
            field=models.IntegerField(choices=[(1, 'CL'), (2, 'ComL'), (3, 'EL'), (4, 'HPL'), (5, 'LA'), (6, 'DL')], default=2),
        ),
        migrations.AlterField(
            model_name='rec',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
