# Generated by Django 2.0 on 2018-02-24 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0020_auto_20180224_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave_request',
            name='is_accepted',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='is_hod',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='is_principal',
        ),
        migrations.AddField(
            model_name='leave_request',
            name='is_accepted_by_hod',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='leave_request',
            name='is_accepted_by_princi',
            field=models.BooleanField(default=False),
        ),
    ]
